### ISSUE TITLE
please state more clearly where the plugin settings are be available once installed

### ISSUE THREAD

**Issue by jjgh** [chrisguitarguy/WP-Robots-Txt#2]
as in title :)
I had to go check that in forums, should be easier to find. Also after some time you just forget it and have to go looking again.

**Comment by chrisguitarguy** [comment]
@jjgh good call and thank you. There's now a link in the plugin list right to the settings: 

![screen shot 2015-05-03 at 5 28 18 pm](https://cloud.githubusercontent.com/assets/1010392/7447033/fda348de-f1b9-11e4-887a-8dd2a786bb48.png)

**Comment by illtellyoulater** [comment]
:+1: thanks :)
